#define JR_PEQ_MACRO(BASECLASS, COLOUR)\
DOUBLES(BASECLASS,COLOUR) = 1;\
TRIPLES(BASECLASS,IR_ILL,COLOUR) = 1;\
TRIPLES(BASECLASS,ILL,COLOUR) = 1;

#define JR_PEQ_LIGHT_MACRO(BASECLASS, COLOUR)\
DOUBLES(BASECLASS,COLOUR) = 1;\
TRIPLES(BASECLASS,IR,COLOUR) = 1;\
TRIPLES(BASECLASS,IR_ILL,COLOUR) = 1;\
TRIPLES(BASECLASS,ILL,COLOUR) = 1;

#define JR_IR_LIGHT_MACRO(BASECLASS, COLOUR)\
DOUBLES(BASECLASS,COLOUR) = 1;\
TRIPLES(BASECLASS,ILL,COLOUR) = 1;

class asdg_SlotInfo;
class asdg_FrontSideRail: asdg_SlotInfo {
    class compatibleItems {
        JR_PEQ_MACRO(PEQ_T,tan)
        JR_PEQ_MACRO(PEQ_R,tan)
        JR_PEQ_MACRO(PEQ_T,black)
        JR_PEQ_MACRO(PEQ_R,black)
        JR_PEQ_MACRO(PEQ_T,tan_camo_tan)
        JR_PEQ_MACRO(PEQ_R,tan_camo_tan)
        JR_PEQ_MACRO(PEQ_T,camo_tan)
        JR_PEQ_MACRO(PEQ_R,camo_tan)
        JR_PEQ_MACRO(PEQ_T,camo_don)
        JR_PEQ_MACRO(PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,camo_don)
        
        JR_IR_LIGHT_MACRO(M600_L,tan)
        JR_IR_LIGHT_MACRO(M600_R,tan)
        JR_IR_LIGHT_MACRO(M600_B,tan)
        JR_IR_LIGHT_MACRO(M600_L,black)
        JR_IR_LIGHT_MACRO(M600_R,black)
        JR_IR_LIGHT_MACRO(M600_B,black)
        JR_IR_LIGHT_MACRO(M600_L,camo_tan)
        JR_IR_LIGHT_MACRO(M600_R,camo_tan)
        JR_IR_LIGHT_MACRO(M600_B,camo_tan)
        JR_IR_LIGHT_MACRO(M600_L,camo_don)
        JR_IR_LIGHT_MACRO(M600_R,camo_don)
        JR_IR_LIGHT_MACRO(M600_B,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,camo_don)
        
        JR_IR_LIGHT_MACRO(M620_L,tan)
        JR_IR_LIGHT_MACRO(M620_R,tan)
        JR_IR_LIGHT_MACRO(M620_B,tan)
        JR_IR_LIGHT_MACRO(M620_L,black)
        JR_IR_LIGHT_MACRO(M620_R,black)
        JR_IR_LIGHT_MACRO(M620_B,black)
        JR_IR_LIGHT_MACRO(M620_L,camo_tan)
        JR_IR_LIGHT_MACRO(M620_R,camo_tan)
        JR_IR_LIGHT_MACRO(M620_B,camo_tan)
        JR_IR_LIGHT_MACRO(M620_L,camo_don)
        JR_IR_LIGHT_MACRO(M620_R,camo_don)
        JR_IR_LIGHT_MACRO(M620_B,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M620_B_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M620_R_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M620_B_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M620_R_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_B_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_R_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_B_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_R_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_B_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_R_PEQ_T,camo_don)
    };
};

class ACWP_troy_105 : asdg_FrontSideRail {
	class compatibleItems {
        JR_PEQ_MACRO(PEQ_T,tan)
        JR_PEQ_MACRO(PEQ_R,tan)
        JR_PEQ_MACRO(PEQ_T,black)
        JR_PEQ_MACRO(PEQ_R,black)
        JR_PEQ_MACRO(PEQ_T,tan_camo_tan)
        JR_PEQ_MACRO(PEQ_R,tan_camo_tan)
        JR_PEQ_MACRO(PEQ_T,camo_tan)
        JR_PEQ_MACRO(PEQ_R,camo_tan)
        JR_PEQ_MACRO(PEQ_T,camo_don)
        JR_PEQ_MACRO(PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(WMLX_T_PEQ_R,camo_don)
        
        JR_IR_LIGHT_MACRO(M600_L,tan)
        JR_IR_LIGHT_MACRO(M600_R,tan)
        JR_IR_LIGHT_MACRO(M600_B,tan)
        JR_IR_LIGHT_MACRO(M600_L,black)
        JR_IR_LIGHT_MACRO(M600_R,black)
        JR_IR_LIGHT_MACRO(M600_B,black)
        JR_IR_LIGHT_MACRO(M600_L,camo_tan)
        JR_IR_LIGHT_MACRO(M600_R,camo_tan)
        JR_IR_LIGHT_MACRO(M600_B,camo_tan)
        JR_IR_LIGHT_MACRO(M600_L,camo_don)
        JR_IR_LIGHT_MACRO(M600_R,camo_don)
        JR_IR_LIGHT_MACRO(M600_B,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(M600_T_PEQ_R,camo_don)
        
        JR_IR_LIGHT_MACRO(M620_L,tan)
        JR_IR_LIGHT_MACRO(M620_R,tan)
        JR_IR_LIGHT_MACRO(M620_B,tan)
        JR_IR_LIGHT_MACRO(M620_L,black)
        JR_IR_LIGHT_MACRO(M620_R,black)
        JR_IR_LIGHT_MACRO(M620_B,black)
        JR_IR_LIGHT_MACRO(M620_L,camo_tan)
        JR_IR_LIGHT_MACRO(M620_R,camo_tan)
        JR_IR_LIGHT_MACRO(M620_B,camo_tan)
        JR_IR_LIGHT_MACRO(M620_L,camo_don)
        JR_IR_LIGHT_MACRO(M620_R,camo_don)
        JR_IR_LIGHT_MACRO(M620_B,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M620_T_PEQ_R,tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,black)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M620_T_PEQ_R,black)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_T_PEQ_R,tan_camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_T_PEQ_R,camo_tan)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_T,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_L_PEQ_R,camo_don)
        JR_PEQ_LIGHT_MACRO(M620_T_PEQ_R,camo_don)
    };
};