modsets:
  # - core:
  #   name: "SOCOMD_Core/@socomd"
  #   mods:
  #     - "./addons/arsenal"
  #     - "./addons/core"
  #     - "./addons/data"
  #     - "./addons/equipment"
  #     - "./addons/factions"
  #     - "./addons/loadouts"
  #     - "./addons/main"
  #     - "./addons/medical"
  #     - "./addons/missions"
  #     - "./addons/qstore"
  #     - "./addons/vehicles_air"
  #     - "./addons/vehicles_land"
  #     - "./addons/vehicles_sea"
  #     - "./addons/weapons"
  #     - "./addons/zeus"
  - content:
    name: "SOCOMD_Core/@socomd_content"
    mods:
      - "./3rd_party/sa_advancedslingloading"
      - "./3rd_party/socomd_asorvs"
      - "./3rd_party/grad_boc"
      - "./3rd_party/plp_containers"
      - "./3rd_party/rgoc"
      - "./3rd_party/ph_tacready"
      - "./3rd_party/rgoc_rhsafrf_compat"
      - "./3rd_party/rgoc_rhsgref_compat"
      - "./3rd_party/rgoc_rhssaf_compat"
      - "./3rd_party/rgoc_rhsusaf_compat"
      - "./3rd_party/usp_interactions_uniforms"
  - content:
    name: "SOCOMD_Core/@socomd_wearables"
    mods:
      # - "./3rd_party/cos_content"
      - "./3rd_party/au_beret_addon"
  - content:
    name: "SOCOMD_Core/@socomd_vehicles"
    mods:
      - "./3rd_party/fgs_prv13"
      - "./3rd_party/fgs_rsp6"
  - content:
    name: "SOCOMD_Extra/@socomd_sounds_library"
    mods:
      - "./3rd_party/socomd_sfx"
  # - hardcore:
  #   name: "SOCOMD_Extra/@socomd_hardcore"
  #   mods:
  #     - "./modsets/socomd_hardcore"
