name = "SOCOMD";
picture = "logo_socomd_ca.paa";
actionName = "GitHub";
action = "https://socomd.com/";
description = "Main SOCOMD mods";
logo = "logo_socomd_ca.paa";
logoOver = "logo_socomd_ca.paa";
author = "SOCOMD J4 Team";
overviewPicture = "logo_socomd_ca.paa";
