#define AIR_INVENTORY \
class TransportWeapons { \
	INVENTORY_VEHICLE_DEFAULT_WEAPONS \
}; \
class TransportMagazines { \
	INVENTORY_VEHICLE_DEFAULT_MAGAZINES \
}; \
class TransportItems { \
	INVENTORY_VEHICLE_DEFAULT_ITEMS \
}; \
class TransportBackpacks { \
	INVENTORY_VEHICLE_DEFAULT_BACKPACKS \
};

class MELB_AH6M;
class SOCOMD_DRAGONFLY_A : MELB_AH6M {
	AIR_INVENTORY
};

class MELB_MH6M;
class SOCOMD_FIREFLY_A : MELB_MH6M {
	AIR_INVENTORY
};

class CUP_B_AH64D_DL_USA;
class SOCOMD_HURRICANE_A : CUP_B_AH64D_DL_USA {
	AIR_INVENTORY
};

class CUP_B_CH47F_USA;
class SOCOMD_NOMAD_A : CUP_B_CH47F_USA {
	AIR_INVENTORY
};

class CUP_B_UH60M_US;
class SOCOMD_WARRIOR_A : CUP_B_UH60M_US {
	AIR_INVENTORY
};