class SOCOMD_Item_Primary_Sapper : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Magazine_Sapper : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_Sapper : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Sapper : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Sapper {};
class SOCOMD_Item_Headgear_Sapper : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_Sapper {};
class SOCOMD_Item_GPS_Sapper : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_Sapper : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Sapper : SOCOMD_Operator_Vest {};