class SOCOMD_Item_Primary_LAT : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Magazine_LAT : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_LAT : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_LAT : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_LAT : HAFM_LAW {};
class SOCOMD_Item_Headgear_LAT : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_LAT {};
class SOCOMD_Item_GPS_LAT : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_LAT : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_LAT : SOCOMD_Operator_Vest {};