class SOCOMD_Item_Primary_Crewman : CUP_smg_MP5A5 {};
class SOCOMD_Item_Primary_Magazine_Crewman : CUP_30Rnd_9x19_MP5 {};
class SOCOMD_Item_Handgun_Crewman : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Crewman : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Crewman {};
class SOCOMD_Item_Headgear_Crewman : H_HelmetCrew_I {};
class SOCOMD_Item_Binocular_Crewman : Binocular {};
class SOCOMD_Item_GPS_Crewman : ItemAndroid {};
class SOCOMD_Item_Uniform_Crewman : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Crewman : VSM_FAPC_Operator_Multicam {};