class SOCOMD_Item_Primary_PJ : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Magazine_PJ : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_PJ : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_PJ : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_PJ {};
class SOCOMD_Item_Headgear_PJ : SOCOMD_Pilot_helmet {};
class SOCOMD_Item_Binocular_PJ : Binocular {};
class SOCOMD_Item_GPS_PJ : ItemAndroid {};
class SOCOMD_Item_Uniform_PJ : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_PJ : VSM_OGA_OD_Vest_2 {};