class SOCOMD_Item_Primary_PatrolLeader : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_Magazine_PatrolLeader : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_PatrolLeader : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_PatrolLeader : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_PatrolLeader {};
class SOCOMD_Item_Headgear_PatrolLeader : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_PatrolLeader : Laserdesignator {};
class SOCOMD_Item_GPS_PatrolLeader : ItemAndroid {};
class SOCOMD_Item_Uniform_PatrolLeader : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_PatrolLeader : SOCOMD_Leader_Vest {};