class SOCOMD_Item_Primary_Grenadier : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_Magazine_Grenadier : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_Grenadier : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Grenadier : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Grenadier {};
class SOCOMD_Item_Headgear_Grenadier : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_Grenadier {};
class SOCOMD_Item_GPS_Grenadier : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_Grenadier : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Grenadier : SOCOMD_2IC_Vest {};