class SOCOMD_Item_Primary_Marsksman : SMA_HK417_16in {};
class SOCOMD_Item_Primary_Magazine_Marsksman : 20Rnd_762x51_Mag {};
class SOCOMD_Item_Handgun_Marsksman : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Marsksman : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Marsksman {};
class SOCOMD_Item_Headgear_Marsksman : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_Marsksman : Binocular {};
class SOCOMD_Item_GPS_Marsksman : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_Marsksman : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Marsksman : SOCOMD_Operator_Vest {};