class SOCOMD_Item_Primary_Medic : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Magazine_Medic {};
class SOCOMD_Item_Handgun_Medic : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Medic : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Medic {};
class SOCOMD_Item_Headgear_Medic : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_Medic : Binocular {};
class SOCOMD_Item_GPS_Medic : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_Medic : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Medic : SOCOMD_Medic_Vest {};