class SOCOMD_Item_Primary_MAT : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Magazine_MAT : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_MAT : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_MAT : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_MAT : SOCOMD_Carl_Gustav {};
class SOCOMD_Item_Headgear_MAT : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_MAT {};
class SOCOMD_Item_GPS_MAT : ItemMicroDAGR {};
class SOCOMD_Item_Uniform_MAT : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_MAT : SOCOMD_Operator_Vest {};