class SOCOMD_Item_Primary_Pilot {};
class SOCOMD_Item_Primary_Magazine_Pilot {};
class SOCOMD_Item_Handgun_Pilot : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_Pilot : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_Pilot {};
class SOCOMD_Item_Headgear_Pilot : SOCOMD_Pilot_helmet {};
class SOCOMD_Item_Binocular_Pilot : Binocular {};
class SOCOMD_Item_GPS_Pilot : ItemcTab {};
class SOCOMD_Item_Uniform_Pilot : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_Pilot : VSM_OGA_OD_Vest_2 {};