class SOCOMD_Item_Primary_TroopLeader : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_Magazine_TroopLeader : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Handgun_TroopLeader : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Magazine_TroopLeader : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Secondary_TroopLeader {};
class SOCOMD_Item_Headgear_TroopLeader : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Binocular_TroopLeader : Laserdesignator {};
class SOCOMD_Item_GPS_TroopLeader : ItemAndroid {};
class SOCOMD_Item_Uniform_TroopLeader : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Vest_TroopLeader : SOCOMD_Leader_Vest {};