class CfgQstoreBlackList {
	class blacklist[]={
		UK3CB_G_KL_Oli
		UK3CB_G_KLR_Oli
		UK3CB_G_Neck_Shemag_KLR_blk
		UK3CB_G_Neck_Shemag_KLR_tan
		UK3CB_G_Neck_Shemag_KL_blk
		UK3CB_G_Neck_Shemag_KL_tan
		UK3CB_G_Neck_Shemag_KR_blk
		UK3CB_G_Neck_Shemag_KR_tan
		UK3CB_G_KR_Oli
		rhssaf_veil_Green
		rhs_acc_rakurspm
		rhs_acc_1p87
		hlc_optic_docterr
		hlc_optic_hensoldtzo_lo
		hlc_optic_hensoldtzo_lo_2d
		hlc_optic_hensoldtzo_lo_docter
		hlc_optic_hensoldtzo_lo_docter_2d
		hlc_optic_hensoldtzo_hi
		hlc_optic_hensoldtzo_hi_2d
		hlc_optic_hensoldtzo_hi_docter
		hlc_optic_hensoldtzo_hi_docter_2d
		rhsusf_acc_anpas13gv1
		rhsusf_acc_anpvs27
		rhsusf_acc_m2a1
		rhsusf_acc_mrds
		rhsusf_acc_mrds_c
		rhsusf_acc_rm05
		rhsusf_acc_rx01_nofilter
		rhsusf_acc_rx01
		rhsusf_acc_rx01_nofilter_tan
		rhsusf_acc_rx01_tan
		hlc_panel_side_ladder_l_black
		hlc_panel_side_ladder_l_desert
		hlc_panel_side_ladder_l_rg
		hlc_panel_side_ladder_l_od
		hlc_panel_side_ladder_l_pride2
		hlc_panel_side_ladder_m_black
		hlc_panel_side_ladder_m_desert
		hlc_panel_side_ladder_m_rg
		hlc_panel_side_ladder_m_od
		hlc_panel_side_ladder_m_pride2
		hlc_panel_side_ladder_s_black
		hlc_panel_side_ladder_s_desert
		hlc_panel_side_ladder_s_rg
		hlc_panel_side_ladder_s_od
		hlc_panel_side_ladder_s_pride2
		hlc_panel_side_magpulxt_black
		hlc_panel_side_magpulxt_desert
		hlc_panel_side_magpulxt_rg
		hlc_panel_side_magpulxt_od
		hlc_panel_side_magpulxt_pride2
		hlc_panel_side_2xxtme_black
		hlc_panel_side_2xxtme_desert
		hlc_panel_side_2xxtme_rg
		hlc_panel_side_2xxtme_od
		hlc_panel_side_4xxtme_black
		hlc_panel_side_4xxtme_desert
		hlc_panel_side_4xxtme_rg
		hlc_panel_side_4xxtme_od
		hlc_panel_side_6xxtme_black
		hlc_panel_side_6xxtme_desert
		hlc_panel_side_6xxtme_rg
		hlc_panel_side_6xxtme_od
		hlc_panel_side_xtme_black
		hlc_panel_side_xtme_desert
		hlc_panel_side_xtme_rg
		hlc_panel_side_xtme_od
		hlc_panel_side_fn10cm_black
		hlc_panel_side_fn10cm_desert
		hlc_panel_side_fn10cm_rg
		hlc_panel_side_fn10cm_od
		hlc_panel_side_fn15cm_black
		hlc_panel_side_fn15cm_desert
		hlc_panel_side_fn15cm_rg
		hlc_panel_side_fn15cm_od
		hlc_panel_side_2xfn5cm_black
		hlc_panel_side_2xfn5cm_desert
		hlc_panel_side_2xfn5cm_rg
		hlc_panel_side_2xfn5cm_od
		hlc_panel_side_fn5cm_black
		hlc_panel_side_fn5cm_desert
		hlc_panel_side_fn5cm_rg
		hlc_panel_side_fn5cm_od
	};
	class socomd[] ={
		rhs_acc_ekp8_18
		rhs_acc_okp7_picatinny
		rhsgref_acc_rx01_nofilter_camo
		rhsgref_acc_rx01_camo
		rhs_acc_2dpzenit_ris
		rhs_acc_perst1ik_ris
		rhs_acc_perst3
		rhs_acc_perst3_illum
	};
};