////////////////////////////////////////////////////////////////////////////////
// MODULAR LOADOUT Russian SF

#define Item_RUSSIAN_PRIMARY_Troopleader        		"SOCOMD_RUS_AK_GL"
#define Item_RUSSIAN_PRIMARY_PatrolLeader       		"SOCOMD_RUS_AK_GL"
#define Item_RUSSIAN_PRIMARY_Rifleman           		"SOCOMD_RUS_AK"
#define Item_RUSSIAN_PRIMARY_Marksman		    		"srifle_DMR_07_blk_F"
#define Item_RUSSIAN_PRIMARY_Medic              		"SOCOMD_RUS_AK"
#define Item_RUSSIAN_PRIMARY_Sapper             		"SOCOMD_RUS_AK"
#define Item_RUSSIAN_PRIMARY_MachineGunner      		"CUP_lmg_Pecheneg"
#define Item_RUSSIAN_PRIMARY_Sniper             		"srifle_DMR_05_blk_F"
#define Item_RUSSIAN_PRIMARY_Recon              		"SOCOMD_RUS_AK"
#define Item_RUSSIAN_PRIMARY_AT                 		"SOCOMD_RUS_AK"
#define Item_RUSSIAN_PRIMARY_Autorifle					"SOCOMD_RUS_RPK"
#define ITEM_RUSSIAN_HANDGUN          					"RH_mak"
#define ITEM_RUSSIAN_SECONDARY_AT						"CUP_launch_RPG18"
#define ITEM_RUSSIAN_SECONDARY_MAT						"SOCOMD_Item_Secondary_MAT"
#define ITEM_RUSSIAN_SECONDARY_HAT						"launch_O_Vorona_green_F"

#define Item_RUSSIAN_PRIMARY_Troopleader_AI      		"SOCOMD_RUS_AK_GL_acc"
#define Item_RUSSIAN_PRIMARY_PatrolLeader_AI   	    	"SOCOMD_RUS_AK_GL_acc"
#define Item_RUSSIAN_PRIMARY_Rifleman_AI            	"SOCOMD_RUS_AK_acc"
#define Item_RUSSIAN_PRIMARY_Marksman_AI		    	"srifle_DMR_07_blk_DMS_F"
#define Item_RUSSIAN_PRIMARY_Medic_AI               	"SOCOMD_RUS_AK_acc"
#define Item_RUSSIAN_PRIMARY_Sapper_AI              	"SOCOMD_RUS_AK_acc"
#define Item_RUSSIAN_PRIMARY_MachineGunner_AI       	"CUP_lmg_Pecheneg"
#define Item_RUSSIAN_PRIMARY_Sniper_AI              	"SOCOMD_RUS_Cyrus_acc"
#define Item_RUSSIAN_PRIMARY_Recon_AI               	"SOCOMD_RUS_AK_acc"
#define Item_RUSSIAN_PRIMARY_AT_AI                  	"SOCOMD_RUS_AK_acc"
#define Item_RUSSIAN_PRIMARY_Autorifle_AI				"SOCOMD_RUS_RPK_acc"

#define Item_RUSSIAN_PRIMARY_MAGAZINE_Troopleader        "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_PatrolLeader       "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Rifleman           "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Marksman		     "ACE_20Rnd_65_Creedmor_mag"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Medic              "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Sapper             "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_MachineGunner      "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Sniper             "10Rnd_93x64_DMR_05_Mag"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Recon              "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_AT                 "CUP_30Rnd_545x39_AK74M_camo_M"
#define Item_RUSSIAN_PRIMARY_MAGAZINE_Autorifle          "SOCOMD_RPK_MAGAZINE"
#define ITEM_RUSSIAN_HANDGUN_MAGAZINE        		     "RH_8Rnd_9x18_Mak"

#define ITEM_RUSSIAN_HEADGEAR               			 "ADFU_H_Airframe_10_OD"
#define ITEM_RUSSIAN_HEADGEAR_SOFT						 "H_Cap_oli_hs"
#define ITEM_RUSSIAN_FACEGEAR               			 "milgp_f_face_shield_tactical_shemagh_RGR"
#define ITEM_RUSSIAN_UNIFORM              				 "SOCOMD_RUS_SleevesDown"
#define ITEM_RUSSIAN_VEST           					 "SOCOMD_RUS_Vest"
#define ITEM_RUSSIAN_BACKPACK_light          			 "backpack_OD"
#define ITEM_RUSSIAN_BACKPACK_heavy           			 "KIT_BAG_Alpin_OD"
#define ITEM_RUSSIAN_BACKPACK_leader           			 "KIT_BAG_R_blk"