#define INVENTORY_VEHICLE_DEFAULT_WEAPONS \
	TRANSPORT_WEAPON(SOCOMD_Item_Primary_Rifleman, 1)

#define INVENTORY_VEHICLE_DEFAULT_MAGAZINES \
	TRANSPORT_MAGAZINE(SOCOMD_Item_Magazine_556x45_30Rnd, 12) \
	TRANSPORT_MAGAZINE(SOCOMD_Item_Magazine_762x51_20Rnd, 3) \
	TRANSPORT_MAGAZINE(SOCOMD_Item_Magazine_556x45_200Rnd_Tracer, 2) \
	TRANSPORT_MAGAZINE(SMA_150Rnd_762_M80A1, 2) \
	TRANSPORT_MAGAZINE(SmokeShellBlue, 2) \
	TRANSPORT_MAGAZINE(B_IR_Grenade, 2)

#define INVENTORY_VEHICLE_DEFAULT_ITEMS \
	TRANSPORT_ITEM(ACRE_PRC152, 1) \
	TRANSPORT_ITEM(ToolKit, 1) \
	TRANSPORT_ITEM(ACE_wirecutter, 1) \
	TRANSPORT_ITEM(ACE_DefusalKit, 1) \
	TRANSPORT_ITEM(ACE_bodyBag, 6) \
	TRANSPORT_ITEM(ACE_CableTie, 6) \
	TRANSPORT_ITEM(ACE_tourniquet, 6)	\
	TRANSPORT_ITEM(ACE_fieldDressing, 20) \
	TRANSPORT_ITEM(ACE_quikclot, 20) \
	TRANSPORT_ITEM(ACE_elasticBandage, 20) \
	TRANSPORT_ITEM(ACE_packingBandage, 20) \
	TRANSPORT_ITEM(ACE_morphine, 10) \
	TRANSPORT_ITEM(ACE_epinephrine, 10) \
	TRANSPORT_ITEM(ACE_surgicalKit, 8)\
	TRANSPORT_ITEM(ACE_bloodIV_500, 5)

#define INVENTORY_VEHICLE_DEFAULT_BACKPACKS \
	TRANSPORT_BACKPACK(SOCOMD_Item_Backpack_Rifleman, 1)