#include "weapons\g3set.hpp"
#include "weapons\ghillies.hpp"
#include "weapons\tshirt.hpp"
#include "weapons\softshell.hpp"
#include "weapons\overwhite.hpp"
#include "weapons\pcu.hpp"
#include "weapons\wetsuits.hpp"
