class SOCOMD_Item_Primary_TroopLeader               : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_PatrolLeader              : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_Rifleman                  : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Grenadier                 : SMA_M4_GL_SM {};
class SOCOMD_Item_Primary_Medic                     : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Sapper                    : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_MachineGunner             : sma_minimi_mk3_762tsb {};
class SOCOMD_Item_Primary_Marsksman                 : SMA_HK417_16in {};
class SOCOMD_Item_Primary_Sniper                    : hlc_rifle_awmagnum {};
class SOCOMD_Item_Primary_LAT                       : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_MAT                       : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_HAT                       : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_PJ                        : SMA_M4afgSTOCK {};
class SOCOMD_Item_Primary_Pilot                     {};
class SOCOMD_Item_Primary_Crewman                   : CUP_smg_MP5A5 {};

class SOCOMD_Item_Primary_Magazine_TroopLeader      : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_PatrolLeader     : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_Rifleman         : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_Grenadier        : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_Medic            {};
class SOCOMD_Item_Primary_Magazine_Sapper           : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_MachineGunner    : SMA_150Rnd_762_M80A1 {};
class SOCOMD_Item_Primary_Magazine_Marsksman        : 20Rnd_762x51_Mag {};
class SOCOMD_Item_Primary_Magazine_Sniper           : hlc_5rnd_300WM_FMJ_AWM {};
class SOCOMD_Item_Primary_Magazine_LAT              : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_MAT              : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_HAT              : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_PJ               : SMA_30Rnd_556x45_M855A1 {};
class SOCOMD_Item_Primary_Magazine_Pilot            {};
class SOCOMD_Item_Primary_Magazine_Crewman          : CUP_30Rnd_9x19_MP5 {};

class SOCOMD_Item_Handgun_TroopLeader               : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_PatrolLeader              : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Rifleman                  : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Grenadier                 : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Medic                     : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Sapper                    : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_MachineGunner             : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Marsksman                 : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Sniper                    : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_LAT                       : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_MAT                       : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_HAT                       : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_PJ                        : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Pilot                     : DSO_hgun_Pistol_heavy_01_blk_F {};
class SOCOMD_Item_Handgun_Crewman                   : DSO_hgun_Pistol_heavy_01_blk_F {};

class SOCOMD_Item_Handgun_Magazine_TroopLeader      : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_PatrolLeader     : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Rifleman         : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Grenadier        : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Medic            : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Sapper           : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_MachineGunner    : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Marsksman        : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Sniper           : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_LAT              : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_MAT              : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_HAT              : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_PJ               : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Pilot            : 11Rnd_45ACP_Mag {};
class SOCOMD_Item_Handgun_Magazine_Crewman          : 11Rnd_45ACP_Mag {};

class SOCOMD_Item_Secondary_TroopLeader             {};
class SOCOMD_Item_Secondary_PatrolLeader            {};
class SOCOMD_Item_Secondary_Rifleman                {};
class SOCOMD_Item_Secondary_Grenadier               {};
class SOCOMD_Item_Secondary_Medic                   {};
class SOCOMD_Item_Secondary_Sapper                  {};
class SOCOMD_Item_Secondary_MachineGunner           {};
class SOCOMD_Item_Secondary_Marsksman               {};
class SOCOMD_Item_Secondary_Sniper                  {};
class SOCOMD_Item_Secondary_LAT                     : HAFM_LAW {};
class SOCOMD_Item_Secondary_MAT                     : SOCOMD_Carl_Gustav {};
class SOCOMD_Item_Secondary_HAT                     : CUP_launch_Javelin {};
class SOCOMD_Item_Secondary_PJ                      {};
class SOCOMD_Item_Secondary_Pilot                   {};
class SOCOMD_Item_Secondary_Crewman                 {};

class SOCOMD_Item_Headgear_TroopLeader              : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_PatrolLeader             : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Rifleman                 : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Grenadier                : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Medic                    : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Sapper                   : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_MachineGunner            : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Marsksman                : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_Sniper                   : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_LAT                      : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_MAT                      : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_HAT                      : ADFU_H_Airframe_Cover_03_MC {};
class SOCOMD_Item_Headgear_PJ                       : SOCOMD_Pilot_helmet {};
class SOCOMD_Item_Headgear_Pilot                    : SOCOMD_Pilot_helmet {};
class SOCOMD_Item_Headgear_Crewman                  : H_HelmetCrew_I {};

class SOCOMD_Item_Binocular_TroopLeader             : Laserdesignator {};
class SOCOMD_Item_Binocular_PatrolLeader            : Laserdesignator {};
class SOCOMD_Item_Binocular_Rifleman                : Binocular {};
class SOCOMD_Item_Binocular_Grenadier               {};
class SOCOMD_Item_Binocular_Medic                   : Binocular {};
class SOCOMD_Item_Binocular_Sapper                  {};
class SOCOMD_Item_Binocular_MachineGunner           {};
class SOCOMD_Item_Binocular_Marsksman               : Binocular {};
class SOCOMD_Item_Binocular_Sniper                  : Binocular {};
class SOCOMD_Item_Binocular_LAT                     {};
class SOCOMD_Item_Binocular_MAT                     {};
class SOCOMD_Item_Binocular_HAT                     {};
class SOCOMD_Item_Binocular_PJ                      : Binocular {};
class SOCOMD_Item_Binocular_Pilot                   : Binocular {};
class SOCOMD_Item_Binocular_Crewman                 : Binocular {};

class SOCOMD_Item_GPS_TroopLeader                   : ItemAndroid {};
class SOCOMD_Item_GPS_PatrolLeader                  : ItemAndroid {};
class SOCOMD_Item_GPS_Rifleman                      : ItemMicroDAGR {};
class SOCOMD_Item_GPS_Grenadier                     : ItemMicroDAGR {};
class SOCOMD_Item_GPS_Medic                         : ItemMicroDAGR {};
class SOCOMD_Item_GPS_Sapper                        : ItemMicroDAGR {};
class SOCOMD_Item_GPS_MachineGunner                 : ItemMicroDAGR {};
class SOCOMD_Item_GPS_Marsksman                     : ItemMicroDAGR {};
class SOCOMD_Item_GPS_Sniper                        : ItemMicroDAGR {};
class SOCOMD_Item_GPS_LAT                           : ItemMicroDAGR {};
class SOCOMD_Item_GPS_MAT                           : ItemMicroDAGR {};
class SOCOMD_Item_GPS_HAT                           : ItemMicroDAGR {};
class SOCOMD_Item_GPS_PJ                            : ItemAndroid {};
class SOCOMD_Item_GPS_Pilot                         : ItemcTab {};
class SOCOMD_Item_GPS_Crewman                       : ItemAndroid {};

class SOCOMD_Item_Uniform_TroopLeader               : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_PatrolLeader              : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Rifleman                  : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Grenadier                 : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Medic                     : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Sapper                    : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_MachineGunner             : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Marsksman                 : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Sniper                    : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_LAT                       : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_MAT                       : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_HAT                       : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_PJ                        : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Pilot                     : SOCOMD_Commando_SleevesDown {};
class SOCOMD_Item_Uniform_Crewman                   : SOCOMD_Commando_SleevesDown {};

class SOCOMD_Item_Vest_TroopLeader                  : SOCOMD_Leader_Vest {};
class SOCOMD_Item_Vest_PatrolLeader                 : SOCOMD_Leader_Vest {};
class SOCOMD_Item_Vest_Rifleman                     : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_Grenadier                    : SOCOMD_2IC_Vest {};
class SOCOMD_Item_Vest_Medic                        : SOCOMD_Medic_Vest {};
class SOCOMD_Item_Vest_Sapper                       : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_MachineGunner                : VSM_LBT6094_MG_Multicam {};
class SOCOMD_Item_Vest_Marsksman                    : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_Sniper                       : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_LAT                          : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_MAT                          : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_HAT                          : SOCOMD_Operator_Vest {};
class SOCOMD_Item_Vest_PJ                           : VSM_OGA_OD_Vest_2 {};
class SOCOMD_Item_Vest_Pilot                        : VSM_OGA_OD_Vest_2 {};
class SOCOMD_Item_Vest_Crewman                      : VSM_FAPC_Operator_Multicam {};

class SOCOMD_Item_Backpack_PatrolLeader             : Kit_Bag_R_MC {};
class SOCOMD_Item_Backpack_TroopLeader              : Kit_Bag_R_MC {};
class SOCOMD_Item_Backpack_Rifleman                 : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_Grenadier                : SOG_BAG_recon_MC {};
class SOCOMD_Item_Backpack_Medic                    : SOG_BAG_med_MC {};
class SOCOMD_Item_Backpack_Sapper                   : Kit_Bag_pince_TAN {};
class SOCOMD_Item_Backpack_MachineGunner            : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_Marsksman                : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_Sniper                   : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_LAT                      : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_MAT                      : SOG_BAG_MC {};
class SOCOMD_Item_Backpack_HAT                      : Kit_Bag_MC {};
class SOCOMD_Item_Backpack_PJ                       : Kit_Bag_MC {};
class SOCOMD_Item_Backpack_Pilot                    : SOG_BAG_recon_od {};
class SOCOMD_Item_Backpack_Crewman                  : KIT_BAG_MC {};
